# .github/workflows/deploy.yml
name: CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Pull Repo
      - uses: actions/checkout@v3

      # Github Secrets에서 API Key 받아온 후 .env 파일에 추가
      - run: |
          echo "OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}}" >> .env
      - run: cat .env

      - run: npm install
      - run: npm run build
